### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by evhumphrey** [tokyosuite/BugMojo#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

- [x] Update your wiki welcome page to have a placeholder link to your live page
- [x] Add a bulleted list of: MVP List, Schema, Sample State, Frontend Routes/Components, Backend Routes that link to those pages
---

# MVP List

- [ ] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- [x] For CRUD, answers (being createable, readable, updateable) also should be delete-able
- [x] Right now you have 6 MVPs. For the four project-specific MVPs, I would have: 1. Questions, 2. Answers, 3. Search, 4. Upvote/Downvote
- [x] I'd move Dashboard/Profile to your first bonus MVP after completing the above
- [x] We can go over schedule of MVPs tomorrow 

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

- [x] `answers` will need a `question_id` so an answer can be associated with a question
- [x] I wouldn't have an `upvotes` column in your `answers` table. Instead, I'd have a `votes` table that is [polymorphic](https://guides.rubyonrails.org/v5.2/association_basics.html#polymorphic-associations)  so questions and answers (and potentially comments down the road) can be upvotable/downvoteable. 

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

- [x] You'll need a `numVotes` key in both your questions and answers slices
- [x] You'll probably need a `hasUserVoted` key in your questions and answers that will store -1, 0, or 1 to represent if the user has downvoted, not voted, or upvoted this particular question or answer already (so your UI can show that). 
- [x] You don't need the `questionIds` array in your users slice of state (instead, you can loop over the questions slice of state, and look for all questions with the userId you have in mind)

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

- [x] I'd update `id` to `:id` to represent that they are wildcards
- [x] You probably won't need any answers endpoints as you will fetch answers when you fetch a question `GET /api/questions/:id`
--- 

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

- [x] I'd change `/question/id` to `/questions/:id` or `/questions/:questionId` (the latter might be easier when you use `match.params`

**Comment by evhumphrey** [comment]
![Screen Shot 2019-07-02 at 2 20 35 PM](https://user-images.githubusercontent.com/6361824/60548748-afa15b80-9cd7-11e9-9b4f-94cfd19baff4.png)
![Screen Shot 2019-07-02 at 2 20 35 PM](https://user-images.githubusercontent.com/6361824/60548752-b0d28880-9cd7-11e9-9fd1-30ca2bd89634.png)

**Comment by tokyosuite** [comment]
Implemented the suggestions. Thanks Elliot!
